"use client"
import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'id' | 'en'

const translations = {
  id: {
    // Sidebar
    adminPanel: "Admin Panel",
    dashboard: "Dasbor",
    users: "Pengguna",
    analytics: "Analitik",
    databases: "Database",
    security: "Keamanan",
    settings: "Pengaturan",
    helpSupport: "Bantuan",
    logout: "Keluar",
    submissions: "Pengajuan",

    // Overview
    totalUsers: "Total Pengguna",
    totalAccess: "Total Akses Jurnal",
    activeDB: "Database Aktif",
    systemUptime: "Uptime Sistem",
    trafficTitle: "Trafik Pengunjung & Akses",
    topDBTitle: "Database Terpopuler",
    userDistTitle: "Distribusi Pengguna",
    recentActivity: "Aktivitas Terbaru",
    last7Days: "7 Hari Terakhir",
    thisMonth: "Bulan Ini",
    thisWeek: "Minggu Ini",
    lastMonth: "Bulan Lalu",
    thisYear: "Tahun Ini",
    vsLastWeek: "vs minggu lalu",
    viewAll: "Lihat Semua",

    // Users
    userMgmt: "Manajemen Pengguna",
    userMgmtDesc: "Kelola data dan hak akses sivitas akademika.",
    addUser: "Tambah User",
    activeUsers: "User Aktif",
    registeredLecturers: "Dosen Terdaftar",
    newThisMonth: "Baru (bulan ini)",
    nameEmail: "Nama & Email",
    faculty: "Fakultas",
    major: "Jurusan",
    role: "Role",
    status: "Status",
    lastAccess: "Akses Terakhir",
    actions: "Aksi",
    allFaculties: "Semua Fakultas",
    allMajors: "Semua Jurusan",
    allRoles: "Semua Role",
    allStatus: "Semua Status",
    activeNow: "Sedang Online",
    addNewUser: "Tambah Pengguna Baru",
    fullName: "Nama Lengkap",
    nimNip: "NIM / NIP",
    emailAccess: "Email Akses",
    defaultPassword: "Password Default",
    selectFaculty: "Pilih Fakultas",
    selectMajor: "Pilih Jurusan",
    selectRole: "Pilih Role",
    saveUser: "Simpan Pengguna",
    saving: "Menyimpan...",
    showing: "Menampilkan",
    of: "dari",

    // Analytics
    keywordTrend: "Tren Kata Kunci",
    platformRanking: "Peringkat Platform",
    downloadTracker: "Pemantau Unduhan",
    keyword: "Kata Kunci",
    frequency: "Frekuensi",
    trend: "Tren",
    topFaculty: "Fakultas Terbanyak",
    accesses: "akses",
    renew: "PERPANJANG",
    evaluate: "EVALUASI",
    downloadsPerDay: "Download / Hari",
    alertExcessDownload: "mengunduh {count} file dalam 1 jam terakhir!",
    investigate: "Investigasi",
    dismiss: "Abaikan",

    // Databases
    journalDirectory: "Direktori Database & Jurnal",
    journalDirectoryDesc: "Atur integrasi publisher dan sumber literatur.",
    addDatabase: "Tambah Database",
    healthCheck: "Status Koneksi Provider",
    autoRefresh: "Auto-refresh dalam",
    refresh: "Refresh",
    dbName: "Nama Database",
    category: "Kategori",
    accessMethod: "Metode Akses",
    urlPortal: "URL Portal",
    uptime: "Uptime",
    proxyConfig: "Konfigurasi Proxy",
    targetUrl: "Target URL",
    proxyPort: "Port Proxy",
    authMethod: "Metode Auth",
    ipWhitelist: "IP Whitelist",
    save: "Simpan",
    testConnection: "Test Koneksi",
    running: "Berjalan",
    lastRestart: "Restart terakhir",

    // Security
    successfulLogins: "Login Sukses",
    failedLogins: "Login Gagal",
    anomaliesDetected: "Anomali Terdeteksi",
    today: "Hari ini",
    anomalyAlerts: "Peringatan Anomali",
    connectionLogs: "Log Koneksi & Keamanan",
    searchLogs: "Cari log...",
    exportCsv: "Ekspor CSV",
    logId: "Log ID",
    user: "Pengguna",
    type: "Tipe",
    ip: "Alamat IP",
    location: "Lokasi",
    time: "Waktu",
    blockUser: "Blokir",
    critical: "KRITIS",
    medium: "MEDIUM",

    // Settings
    profileSettings: "Profil Admin",
    accessConfig: "Konfigurasi Jalur Akses",
    idpSettings: "Integrasi Keycloak / IdP",
    notifPrefs: "Preferensi Notifikasi",
    appearance: "Tampilan & Bahasa",

    // Notifications
    notifications: "Notifikasi Terbaru",
    unreadMessages: "pesan baru",
    readAll: "BACA SEMUA",
    search: "Cari fitur, pengguna, atau ID...",

    // Common
    active: "Aktif",
    inactive: "Nonaktif",
    maintenance: "Maintenance",
    down: "Down",
    blocked: "Terblokir",
    edit: "Edit",
    delete: "Hapus",
    deactivate: "Nonaktifkan",
    cancel: "Batal",
    confirm: "Konfirmasi",
    save: "Simpan",
    back: "Kembali",
    continue: "Lanjutkan",
    approved: "Disetujui",
    rejected: "Ditolak",
    pending: "Pending",
    all: "Semua",
    online: "Online",
    offline: "Offline",

    // Databases Page
    databaseDirectory: "Direktori Database",
    manageDatabasesDesc: "Kelola koneksi database dan logika provider.",
    searchDatabasePlaceholder: "Cari database...",
    journalRecords: "Rekaman Jurnal",
    manageJournalsDesc: "Kelola artikel jurnal dan publikasi individu.",
    addJournal: "Tambah Jurnal",
    searchJournalPlaceholder: "Cari jurnal berdasarkan judul atau penerbit...",
    journalTitle: "Judul Jurnal",
    publisher: "Penerbit",
    updatedDate: "Tanggal Diperbarui",
    expiryDate: "Tanggal Kedaluwarsa",
    ebookRepository: "Repositori eBook",
    manageEbooksDesc: "Kelola buku digital dan paket eBook.",
    addEbook: "Tambah eBook",
    searchEbookPlaceholder: "Cari eBook berdasarkan judul atau penerbit...",
    ebookTitle: "Judul eBook",
    date: "Tanggal",

    // Calendar & Filters
    january: "Januari", february: "Februari", march: "Maret", april: "April", may: "Mei", june: "Juni",
    july: "Juli", august: "Agustus", september: "September", october: "Oktober", november: "November", december: "Desember",
    janShort: "Jan", febShort: "Feb", marShort: "Mar", aprShort: "Apr", mayShort: "Mei", junShort: "Jun",
    julShort: "Jul", augShort: "Agu", sepShort: "Sep", octShort: "Okt", novShort: "Nov", decShort: "Des",
    sunShort: "Min", monShort: "Sen", tueShort: "Sel", wedShort: "Rab", thuShort: "Kam", friShort: "Jum", satShort: "Sab",
    clear: "Bersihkan",
    today: "Hari Ini",
    selectDate: "Pilih Tanggal",
    selectRange: "Pilih Rentang",
    singleDate: "Tanggal Tunggal",
    dateRange: "Rentang Tanggal",
    daily: "Harian",
    weekly: "Mingguan",
    monthly: "Bulanan",
    yearly: "Tahunan",
    updateGranularity: "Perbarui Granularitas",
    granularityNote: "Mohon gunakan ikon Kalender di sebelah kiri untuk mengatur tanggal atau rentang {granularity} khusus.",
    exportAsPDF: "Ekspor sebagai PDF",
    exportAsCSV: "Ekspor sebagai CSV",
    exportAsExcel: "Ekspor sebagai Excel",
    exports: "Ekspor",

    // Access Modal
    select: "Pilih",
    configure: "Konfigurasi",
    review: "Tinjau",
    addNew: "Tambah Baru",
    userCategory: "Kategori Pengguna",
    eResourceGroup: "Grup eResource",
    completeSetupProcess: "Selesaikan proses pengaturan",
    eResourceGroupInfo: "Informasi Grup eResource",
    availableResources: "Sumber Daya Tersedia",
    pleaseSelectAtLeastOne: "Mohon pilih setidaknya satu {item}",
    resource: "Sumber Daya",
    selectAll: "Pilih Semua",
    selected: "Terpilih",
    clearAll: "Hapus Semua",
    noItemsSelected: "Tidak ada item terpilih",
    title: "Judul",
    titleRequired: "judul wajib diisi",
    categoryPlaceholder: "contoh: Mahasiswa S1",
    groupPlaceholder: "contoh: Paket Sains & Teknologi",
    pdfLimitNote: "Catatan: Batas PDF mungkin membutuhkan waktu beberapa menit untuk sinkronisasi.",
    reviewFinalize: "Tinjau & Selesaikan",
    deploymentSummary: "Ringkasan Penerapan",
    action: "Aksi",
    addXitems: "Tambah {count} {item}",
    categories: "Kategori",
    databases: "Database",
    default: "Default",
    expiryConfig: "Konfigurasi Kedaluwarsa",
    notSet: "Belum Diatur",
    finalizeSetup: "Selesaikan Pengaturan",

    // Notifications & Dashboard
    updatingDashboard: "Memperbarui dasbor...",
    fetchingLatestData: "Mengambil data terbaru berdasarkan filter Anda",
    dataLoaded: "Data dimuat",
    dashboardMetricsUpdated: "Metrik dasbor telah berhasil diperbarui",
    exportingX: "Mengekspor {format}",
    generatingFileForX: "Menghasilkan file untuk {date} pada resolusi {resolution}",
    pageviews: "Tayangan Halaman",
    visitors: "Pengunjung",
    showingXofY: "Menampilkan {count} dari {total}",
    adminRole: "Role Admin",
    userRole: "Role User",
    accessType: "Tipe Akses",

    // Confirmation
    confirmDeleteTitle: "Hapus {name}?",
    confirmDeleteDesc: "Apakah Anda yakin ingin menghapus {name} secara permanen?",
    confirmDeleteBulkTitle: "Hapus {count} item ini?",
    confirmDeleteBulkDesc: "Apakah Anda yakin ingin menghapus {count} item secara permanen?",
    confirmBulkStatusTitle: "Set {status} {count} item ini?",
    confirmBulkStatusDesc: "Ubah status {count} item menjadi {status}?",
    confirmBulkInactiveTitle: "Nonaktifkan {count} item ini?",
    confirmBulkInactiveDesc: "Apakah Anda yakin ingin menonaktifkan {count} item ini?",
    deleteAll: "Hapus Semua",
    deactivateAll: "Nonaktifkan Semua",
    changeStatus: "Ubah Status",
    confirmBlockTitle: "Blokir user ini?",
    confirmBlockDesc: "User tidak akan bisa mengakses portal lagi.",
    confirmUnblockTitle: "Buka blokir?",
    confirmUnblockDesc: "Akses user akan dipulihkan kembali.",
    confirmStatusTitle: "Ubah status?",
    confirmStatusDesc: "Status item akan diperbarui ke sistem.",
    confirmLogoutTitle: "Keluar dari sistem?",
    confirmLogoutDesc: "Sesi Anda akan berakhir.",
    confirmBulkDelete: "Hapus {count} item terpilih?",
    confirmBulkStatus: "Ubah status {count} item terpilih?",

    // UI Elements
    noData: "Tidak ada data ditemukan",
    searchPlaceholder: "Cari...",
    loading: "Memuat...",
    itemsSelected: "{count} item dipilih",
    showingRange: "Menampilkan {from}-{to} dari {total}",
    bulkImport: "Impor Massal",
    exportData: "Ekspor Data",
    editMode: "Mode Edit",
    bulkAction: "Aksi Massal",

    // User/Access Specific
    userCategories: "Kategori User",
    eResourceGroups: "Grup eResource",
    adminMgmt: "Manajemen Admin",
    accessMgmt: "Manajemen Akses",
    allUsers: "Semua User",
    allAdmins: "Semua Admin",
    addCategory: "Tambah Kategori",
    addGroup: "Tambah Grup",
    type: "Tipe",
    usageRules: "Aturan Pakai",
    accessGroups: "Grup Akses",
    expiry: "Masa Berlaku",
    idNim: "ID / NIM",
    student: "Mahasiswa",
    lecturer: "Dosen",
    researcher: "Peneliti",
    staff: "Staf",
    instituteAdmin: "Admin Institusi",
    instituteSubadmin: "Subadmin Institusi",
    mappedDatabases: "Database Terpetakan",
    usageMetrics: "Metrik Penggunaan",
    pdfLimit: "Batas PDF",
    dataLimit: "Batas Data",
    searchUserPlaceholder: "Cari nama, email, atau ID...",
    searchCategoryPlaceholder: "Cari judul kategori...",
    searchGroupPlaceholder: "Cari nama grup...",
    noUsersFound: "Pengguna tidak ditemukan",
    adjustFilters: "Coba sesuaikan filter Anda",
    onlineNow: "Sedang Online",

    // Page descriptions
    overviewDesc: "Pantau performa dan statistik sistem secara keseluruhan.",
    usersDesc: "Kelola akun pengguna, role, dan izin akses.",
    analyticsDesc: "Analisis tren riset, kata kunci, dan perilaku akses.",
    databasesDesc: "Kelola koneksi ke provider jurnal dan literatur.",
    securityDesc: "Pantau log keamanan, koneksi, dan anomali sistem.",
    settingsDesc: "Konfigurasi sistem dan preferensi admin.",
    submissionsDesc: "Kelola permintaan artikel dan saran pembelian buku.",

    // Users Additional
    lastActivity: "Aktivitas Terakhir",
    customCategory: "Kategori Kustom",
    wasStatus: "sebelumnya: {status}",
    expiryShort: "Kadaluarsa: {date}",
    activate: "Aktifkan",
    setInactive: "Nonaktifkan",
    block: "Blokir",
    delete: "Hapus",
    deactivateAll: "Nonaktifkan Semua",
    deleteAll: "Hapus Semua",
    userManagement: "Manajemen User",
    adminManagement: "Manajemen Admin",
    accessManagement: "Manajemen Akses",
    allUsers: "Semua User",
    active: "Aktif",
    inactive: "Nonaktif",
    blocked: "Terblokir",
    allAdmins: "Semua Admin",
    userCategories: "Kategori User",
    eResourceGroups: "Grup e-Resource",
    groupUpdated: "Grup Diperbarui",
    groupActivated: "Grup Diaktifkan",

    // Notifications
    userCreated: "User berhasil dibuat",
    userUpdated: "Data user diperbarui",
    userDeleted: "User berhasil dihapus",
    usersDeleted: "{count} user berhasil dihapus",
    actionSuccess: "Aksi Berhasil",
    actionFailed: "Aksi Gagal",
    databaseUpdated: "Database diperbarui",
    databasesAdded: "Database berhasil ditambahkan",
    databaseDeleted: "Database dihapus",
    journalsDeleted: "{count} jurnal dihapus",
    bulkActiveSuccess: "Aktivasi massal berhasil",
    bulkInactiveSuccess: "Deaktivasi massal berhasil",
    exportSuccess: "Ekspor Berhasil",
    exportPreparing: "Menyiapkan {count} data...",

    // Analytics Detailed
    appAnalytics: "Analitik Aplikasi",
    userAnalytics: "Analitik Pengguna",
    trendReports: "Laporan Tren",
    totalSearches: "Total Pencarian",
    mostSearched: "Paling Dicari",
    peakAccessDay: "Hari Akses Puncak",
    quickInsights: "Wawasan Cepat",
    viewTrendDetails: "Lihat Detail Tren",
    analysisDesc: "Pelaporan riset mendalam dan analitik perilaku",

    // Search Page
    searchResults: "Hasil Pencarian",
    showingXMatchesForY: "Menampilkan {count} hasil untuk {query}",
    noMatchesFound: "Hasil tidak ditemukan.",
    goBack: "Kembali",
    analyticsKeywords: "Kata Kunci Analitik",
    startSearching: "Mulai mencari...",
    enterKeyword: "Masukkan kata kunci di bilah pencarian di atas untuk menemukan apa yang Anda cari.",

    // Security Detailed
    securitySummary: "Ringkasan Keamanan",
    authTrendAnalysis: "Analisis tren autentikasi 7 hari",
    activeBlockedIps: "IP Terblokir Aktif",
    restrictedIpsDesc: "Alamat IP yang saat ini dibatasi",
    activeBans: "{count} pemblokiran aktif",
    unblockNetwork: "Buka Blokir Jaringan",
    threatMonitoring: "Sistem pemantauan ancaman real-time dan penandaan otomatis",
    allAlerts: "Semua Peringatan",
    viewAllAlerts: "Lihat Semua Peringatan",
    noActiveAnomalies: "Tidak ada anomali aktif",
    ecosystemClear: "Ekosistem saat ini bersih dari pelanggaran ambang batas jaringan atau ancaman keamanan aktif.",
    investigated: "Telah Diinvestigasi",
    auditTrailing: "Audit trailing terperinci untuk sesi fisik dan jarak jauh",
    logic: "Logika",
    ok: "OK",
    fail: "GAGAL",
    lookupIp: "Lookup IP",
    isp: "ISP",
    country: "Negara",
    threatLevel: "Tingkat Ancaman",
    blockRemoteIp: "Blokir IP Jarak Jauh",
    alertHistory: "Riwayat Peringatan",
    clearAllRecords: "Hapus Semua Catatan",
    noPastAlerts: "Tidak Ada Peringatan Lampau",
    investigating: "Sedang Menginvestigasi",

    // Submissions Detailed
    articleRequest: "Permintaan Artikel",
    purchaseSuggestion: "Saran Pembelian",
    submissionDetail: "Detail Pengajuan",
    submitted: "Dikirim",
    requestDetail: "Detail Permintaan",
    titleArticle: "Judul/Artikel",
    bookTitle: "Judul Buku",
    notes: "Catatan",
    noNotesProvided: "Tidak ada catatan.",
    approve: "Setujui",
    reject: "Tolak",
    noSubmissionsMatch: "Tidak ada pengajuan yang cocok dengan filter Anda",
    clearFilters: "Bersihkan filter",
  },
  en: {
    // Sidebar
    adminPanel: "Admin Panel",
    dashboard: "Dashboard",
    users: "Users",
    analytics: "Analytics",
    databases: "Databases",
    security: "Security",
    settings: "Settings",
    helpSupport: "Help & Support",
    logout: "Log Out",
    submissions: "Form Submissions",

    // Overview
    totalUsers: "Total Users",
    totalAccess: "Total Journal Access",
    activeDB: "Active Databases",
    systemUptime: "System Uptime",
    trafficTitle: "Visitor Traffic & Access",
    topDBTitle: "Top Databases",
    userDistTitle: "User Distribution",
    recentActivity: "Recent Activity",
    last7Days: "Last 7 Days",
    thisMonth: "This Month",
    thisWeek: "This Week",
    lastMonth: "Last Month",
    thisYear: "This Year",
    vsLastWeek: "vs last week",
    viewAll: "View All",

    // Users
    userMgmt: "User Management",
    userMgmtDesc: "Manage user accounts, roles, and access permissions.",
    addUser: "Add User",
    activeUsers: "Active Users",
    registeredLecturers: "Lecturers",
    newThisMonth: "New (this month)",
    nameEmail: "Name & Email",
    faculty: "Faculty",
    major: "Major",
    role: "Role",
    status: "Status",
    lastAccess: "Last Access",
    actions: "Actions",
    allFaculties: "All Faculties",
    allMajors: "All Majors",
    allRoles: "All Roles",
    allStatus: "All Status",
    activeNow: "Online Now",
    addNewUser: "Add New User",
    fullName: "Full Name",
    nimNip: "Student / Staff ID",
    emailAccess: "Access Email",
    defaultPassword: "Default Password",
    selectFaculty: "Select Faculty",
    selectMajor: "Select Major",
    selectRole: "Select Role",
    saveUser: "Save User",
    saving: "Saving...",
    showing: "Showing",
    of: "of",

    // Analytics
    keywordTrend: "Keyword Trends",
    platformRanking: "Platform Ranking",
    downloadTracker: "Download Tracker",
    keyword: "Keyword",
    frequency: "Frequency",
    trend: "Trend",
    topFaculty: "Top Faculty",
    accesses: "accesses",
    renew: "RENEW",
    evaluate: "EVALUATE",
    downloadsPerDay: "Downloads / Day",
    alertExcessDownload: "downloaded {count} files in the last hour!",
    investigate: "Investigate",
    dismiss: "Dismiss",

    // Databases
    journalDirectory: "Database & Journal Directory",
    journalDirectoryDesc: "Manage publisher integrations and literature sources.",
    addDatabase: "Add Database",
    healthCheck: "Provider Connection Status",
    autoRefresh: "Auto-refresh in",
    refresh: "Refresh",
    dbName: "Database Name",
    category: "Category",
    accessMethod: "Access Method",
    urlPortal: "Portal URL",
    uptime: "Uptime",
    proxyConfig: "Proxy Configuration",
    targetUrl: "Target URL",
    proxyPort: "Proxy Port",
    authMethod: "Auth Method",
    ipWhitelist: "IP Whitelist",
    save: "Save",
    testConnection: "Test Connection",
    running: "Running",
    lastRestart: "Last restart",

    // Security
    successfulLogins: "Successful Logins",
    failedLogins: "Failed Logins",
    anomaliesDetected: "Anomalies Detected",
    today: "Today",
    anomalyAlerts: "Anomaly Alerts",
    connectionLogs: "Connection & Security Logs",
    searchLogs: "Search logs...",
    exportCsv: "Export CSV",
    logId: "Log ID",
    user: "User",
    type: "Type",
    ip: "IP Address",
    location: "Location",
    time: "Time",
    blockUser: "Block",
    critical: "CRITICAL",
    medium: "MEDIUM",

    // Settings
    profileSettings: "Admin Profile",
    accessConfig: "Access Path Configuration",
    idpSettings: "Keycloak / IdP Integration",
    notifPrefs: "Notification Preferences",
    appearance: "Appearance & Language",

    // Notifications
    notifications: "Recent Notifications",
    unreadMessages: "new messages",
    readAll: "READ ALL",
    search: "Search features, users, or IDs...",

    // Common
    active: "Active",
    inactive: "Inactive",
    maintenance: "Maintenance",
    down: "Down",
    blocked: "Blocked",
    edit: "Edit",
    delete: "Delete",
    deactivate: "Deactivate",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    back: "Back",
    continue: "Continue",
    approved: "Approved",
    rejected: "Rejected",
    pending: "Pending",
    all: "All",
    online: "Online",
    offline: "Offline",

    // Databases Page
    databaseDirectory: "Database Directory",
    manageDatabasesDesc: "Manage database connections and provider logic.",
    searchDatabasePlaceholder: "Search databases...",
    journalRecords: "Journal Records",
    manageJournalsDesc: "Manage individual journal articles and publications.",
    addJournal: "Add Journal",
    searchJournalPlaceholder: "Search journals by title or publisher...",
    journalTitle: "Journal Title",
    publisher: "Publisher",
    updatedDate: "Updated Date",
    expiryDate: "Expiry Date",
    ebookRepository: "eBook Repository",
    manageEbooksDesc: "Manage digital books and packages.",
    addEbook: "Add eBook",
    searchEbookPlaceholder: "Search eBooks by title or publisher...",
    ebookTitle: "eBook Title",
    date: "Date",

    // Calendar & Filters
    january: "January", february: "February", march: "March", april: "April", may: "May", june: "June",
    july: "July", august: "August", september: "September", october: "October", november: "November", december: "December",
    janShort: "Jan", febShort: "Feb", marShort: "Mar", aprShort: "Apr", mayShort: "May", junShort: "Jun",
    julShort: "Jul", augShort: "Aug", sepShort: "Sep", octShort: "Oct", novShort: "Nov", decShort: "Dec",
    sunShort: "Su", monShort: "Mo", tueShort: "Tu", wedShort: "We", thuShort: "Th", friShort: "Fr", satShort: "Sa",
    clear: "Clear",
    today: "Today",
    selectDate: "Select Date",
    selectRange: "Select Range",
    singleDate: "Single Date",
    dateRange: "Date Range",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    updateGranularity: "Update Granularity",
    granularityNote: "Please use the Calendar icon on the left to set custom {granularity} dates or ranges.",
    exportAsPDF: "Export as PDF",
    exportAsCSV: "Export as CSV",
    exportAsExcel: "Export as Excel",
    exports: "Exports",

    // Access Modal
    select: "Select",
    configure: "Configure",
    review: "Review",
    addNew: "Add New",
    userCategory: "User Category",
    eResourceGroup: "eResource Group",
    completeSetupProcess: "Complete the setup process",
    eResourceGroupInfo: "eResource Group Information",
    availableResources: "Available Resources",
    pleaseSelectAtLeastOne: "Please select at least one {item}",
    resource: "Resource",
    selectAll: "Select All",
    selected: "Selected",
    clearAll: "Clear All",
    noItemsSelected: "No items selected",
    title: "Title",
    titleRequired: "title is required",
    categoryPlaceholder: "e.g. Undergraduate Student",
    groupPlaceholder: "e.g. Science & Technology Bundle",
    pdfLimitNote: "Note: PDF limit enforcement may take a few minutes after the user reaches the specified limit.",
    reviewFinalize: "Review & Finalize",
    deploymentSummary: "Deployment Summary",
    action: "Action",
    addXitems: "Add {count} {item}",
    categories: "Categories",
    databases: "Database(s)",
    default: "Default",
    expiryConfig: "Expiry Config",
    notSet: "Not Set",
    finalizeSetup: "Finalize Setup",

    // Notifications & Dashboard
    updatingDashboard: "Updating dashboard...",
    fetchingLatestData: "Fetching latest data based on your filters",
    dataLoaded: "Data loaded",
    dashboardMetricsUpdated: "Dashboard metrics have been successfully updated",
    exportingX: "Exporting {format}",
    generatingFileForX: "Generating file for {date} at {resolution} resolution",
    pageviews: "Pageviews",
    visitors: "Visitors",
    showingXofY: "Showing {count} of {total}",
    adminRole: "Admin Role",
    userRole: "User Role",
    accessType: "Access Type",

    // Confirmation
    confirmDeleteTitle: "Delete {name}?",
    confirmDeleteDesc: "Are you sure you want to delete {name} permanently?",
    confirmDeleteBulkTitle: "Delete these {count} items?",
    confirmDeleteBulkDesc: "Are you sure you want to delete these {count} items permanently?",
    confirmBulkStatusTitle: "Set these {count} items to {status}?",
    confirmBulkStatusDesc: "Change the status of {count} items to {status}?",
    confirmBulkInactiveTitle: "Deactivate these {count} items?",
    confirmBulkInactiveDesc: "Are you sure you want to deactivate these {count} items?",
    deleteAll: "Delete All",
    deactivateAll: "Deactivate All",
    changeStatus: "Change Status",
    confirmBlockTitle: "Block this user?",
    confirmBlockDesc: "User will no longer be able to access the portal.",
    confirmUnblockTitle: "Unblock user?",
    confirmUnblockDesc: "User access will be fully restored.",
    confirmStatusTitle: "Change status?",
    confirmStatusDesc: "Item status will be updated in the system.",
    confirmLogoutTitle: "Sign out of system?",
    confirmLogoutDesc: "Your active session will be ended.",
    confirmBulkDelete: "Delete {count} selected items?",
    confirmBulkStatus: "Change status for {count} items?",

    // UI Elements
    noData: "No data found",
    searchPlaceholder: "Search...",
    loading: "Loading...",
    itemsSelected: "{count} items selected",
    showingRange: "Showing {from}-{to} of {total}",
    bulkImport: "Bulk Import",
    exportData: "Export Data",
    editMode: "Edit Mode",
    bulkAction: "Bulk Action",

    // User/Access Specific
    userCategories: "User Categories",
    eResourceGroups: "eResource Groups",
    adminMgmt: "Admin Management",
    accessMgmt: "Access Management",
    allUsers: "All Users",
    allAdmins: "All Admins",
    addCategory: "Add Category",
    addGroup: "Add Group",
    type: "Type",
    usageRules: "Usage Rules",
    accessGroups: "Access Groups",
    expiry: "Expiry",
    idNim: "ID / ID Number",
    student: "Student",
    lecturer: "Lecturer",
    researcher: "Researcher",
    staff: "Staff",
    instituteAdmin: "Institute Admin",
    instituteSubadmin: "Institute Subadmin",
    mappedDatabases: "Mapped Databases",
    usageMetrics: "Usage Metrics",
    pdfLimit: "PDF Limit",
    dataLimit: "Data Limit",
    searchUserPlaceholder: "Search name, email, or ID...",
    searchCategoryPlaceholder: "Search category title...",
    searchGroupPlaceholder: "Search group name...",
    noUsersFound: "No users found",
    adjustFilters: "Try adjusting your filters",
    onlineNow: "Online Now",

    // Page descriptions
    overviewDesc: "Monitor overall system performance and statistics.",
    usersDesc: "Manage user accounts, roles, and access permissions.",
    analyticsDesc: "Analyze research trends, keywords, and access behavior.",
    databasesDesc: "Manage connections to journal and literature providers.",
    securityDesc: "Monitor security logs, connections, and system anomalies.",
    settingsDesc: "System configuration and admin preferences.",
    submissionsDesc: "Manage article requests and purchase suggestions.",

    // Users Additional
    lastActivity: "Last Activity",
    customCategory: "Custom Category",
    wasStatus: "was: {status}",
    expiryShort: "Exp: {date}",
    activate: "Activate",
    setInactive: "Set Inactive",
    block: "Block",
    delete: "Delete",
    deactivateAll: "Deactivate All",
    deleteAll: "Delete All",
    userManagement: "User Management",
    adminManagement: "Admin Management",
    accessManagement: "Access Management",
    allUsers: "All Users",
    active: "Active",
    inactive: "Inactive",
    blocked: "Blocked",
    allAdmins: "All Admins",
    userCategories: "User Categories",
    eResourceGroups: "eResource Groups",
    groupUpdated: "Group Updated",
    groupActivated: "Group Activated",

    // Notifications
    userCreated: "User created successfully",
    userUpdated: "User data updated",
    userDeleted: "User deleted successfully",
    usersDeleted: "{count} users deleted",
    actionSuccess: "Action Success",
    actionFailed: "Action Failed",
    databaseUpdated: "Database updated",
    databasesAdded: "Databases added successfully",
    databaseDeleted: "Database deleted",
    journalsDeleted: "{count} journals deleted",
    bulkActiveSuccess: "Bulk activation successful",
    bulkInactiveSuccess: "Bulk deactivation successful",
    exportSuccess: "Export Successful",
    exportPreparing: "Preparing {count} records...",

    // Analytics Detailed
    appAnalytics: "App Analytics",
    userAnalytics: "User Analytics",
    trendReports: "Trend Reports",
    totalSearches: "Total Searches",
    mostSearched: "Most Searched",
    peakAccessDay: "Peak Access Day",
    quickInsights: "Quick Insights",
    viewTrendDetails: "View Trend Details",
    analysisDesc: "Deep-dive research reporting and behavioral analytics",

    // Search Page
    searchResults: "Search Results",
    showingXMatchesForY: "Showing {count} matches for {query}",
    noMatchesFound: "No matches found.",
    goBack: "Go back",
    analyticsKeywords: "Analytics Keywords",
    startSearching: "Start searching...",
    enterKeyword: "Enter a keyword in the search bar above to find what you're looking for.",

    // Security Detailed
    securitySummary: "Security Summary",
    authTrendAnalysis: "7-day authentication trend analysis",
    activeBlockedIps: "Active Blocked IPs",
    restrictedIpsDesc: "IP addresses currently restricted",
    activeBans: "{count} active bans",
    unblockNetwork: "Unblock Network",
    threatMonitoring: "Real-time threat monitoring and auto-flagging system",
    allAlerts: "All Alerts",
    viewAllAlerts: "View All Alerts",
    noActiveAnomalies: "No active anomalies",
    ecosystemClear: "The ecosystem is currently clear of any active network thresholds or security threat violations.",
    investigated: "Investigated",
    auditTrailing: "Detailed audit trailing for physical and remote sessions",
    logic: "Logic",
    ok: "OK",
    fail: "FAIL",
    lookupIp: "IP Lookup",
    isp: "ISP",
    country: "Country",
    threatLevel: "Threat Level",
    blockRemoteIp: "Block Remote IP",
    alertHistory: "Alert History",
    clearAllRecords: "Clear All Records",
    noPastAlerts: "No Past Alerts",
    investigating: "Investigating",

    // Submissions Detailed
    articleRequest: "Article Request",
    purchaseSuggestion: "Purchase Suggestion",
    submissionDetail: "Submission Detail",
    submitted: "Submitted",
    requestDetail: "Request Detail",
    titleArticle: "Title/Article",
    bookTitle: "Book Title",
    notes: "Notes",
    noNotesProvided: "No notes provided.",
    approve: "Approve",
    reject: "Reject",
    noSubmissionsMatch: "No submissions match your filters",
    clearFilters: "Clear filters",
  }
}

export type Translations = typeof translations['id']

const LanguageContext = createContext<{
  lang: Language
  t: Translations
  toggleLang: () => void
  setLanguage: (l: Language) => void
} | undefined>(undefined)

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>('id')
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const saved = localStorage.getItem('appLang') as Language
    if ((saved === 'en' || saved === 'id') && saved !== lang) setLang(saved)
  }, [lang])

  const toggleLang = () => {
    const newLang = lang === 'id' ? 'en' : 'id'
    setLang(newLang)
    localStorage.setItem('appLang', newLang)
  }

  const setLanguage = (newLang: Language) => {
    setLang(newLang)
    localStorage.setItem('appLang', newLang)
  }

  return (
    <LanguageContext.Provider value={{ lang, t: translations[lang], toggleLang, setLanguage }}>
      <div style={!mounted ? { visibility: 'hidden' } : undefined} suppressHydrationWarning>
        {children}
      </div>
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used within LanguageProvider")
  return context
}
